stages:
  - vs: "./shaders/1_vertex.glsl"
    mode: "LINE_STRIP"
    line_width: 2
    count: 1000
    target: "vertex"
    
  - fs: "./shaders/2_scene1.glsl"
    target: "scene1"
  
  - fs: "./shaders/3_logo.glsl"
    target: "logo_layer"

  - fs: "./shaders/4_raytracing.glsl"
    target: "raytracing"
    float: true

  - fs: "./shaders/5_accumulate_layer.glsl"
    target: "accumulate_layer"
    float: true

  - fs: "./shaders/6_combine_layer.glsl"
    target: "combine_layer"
  
  - fs: "./shaders/7_tv.glsl"
    target: "tv_layer"

  - fs: "./shaders/8_pixelflow.glsl"
    target: "pixelflow_layer"

  - fs: "./shaders/bloom_layer.glsl"
    target: "bloom_layer"

  - fs: "./shaders/bloom_layer_gauss.glsl"
    target: "bloom_gauss"

  - fs: "./shaders/bloom_layer_combine.glsl"
    target: "bloom_combine"

  - fs: "./shaders/postEffect_layer.glsl"

ndi:
  - source: "0youtube-spout"
    name: "NDI_0"
  - source: "1youtube-spout"
    name: "NDI_1"

images:
   - path: "./img/hypnosynth_logo_white.png"
     name: "PlotLogo"
   - path: "./img/VAT_Umishida.png"
     name: "VAT_test"
     filter: nearest
