stages:
  - vs: "./shaders/1_vertex.glsl"
    mode: "LINE_STRIP"
    line_width: 2
    count: 1000
    target: "vertex"
    
  - fs: "./shaders/2_scene1.glsl"
    resolution: [1440,1080]
    target: "scene1"
  
  - fs: "./shaders/4_raytracing.glsl"
    resolution: [1440,1080]
    target: "raytracing"
    float: true
    
  - fs: "./shaders/3_logo.glsl"
    resolution: [1440,1080]
    target: "logo_layer"


  - fs: "./shaders/5_accumulate_layer.glsl"
    resolution: [1440,1080]
    target: "accumulate_layer"
    float: true

  - fs: "./shaders/6_combine_layer.glsl"
    resolution: [1440,1080]
    target: "combine_layer"
  
  - fs: "./shaders/7_tv.glsl"
    target: "tv_layer"

  - fs: "./shaders/8_pixelflow.glsl"
    target: "pixelflow_layer"

  - fs: "./shaders/bloom_layer.glsl"
    target: "bloom_layer"

  - fs: "./shaders/bloom_layer_gauss.glsl"
    target: "bloom_gauss"

  - fs: "./shaders/bloom_layer_combine.glsl"
    target: "bloom_combine"

  - fs: "./shaders/postEffect_layer.glsl"

audio:
  audio_samples: 1000
  spectrum:
    mipmap: true
    filter: linear
    wrap_mode: repeat

ndi:
  - source: "0youtube-spout"
    name: "NDI_0"

images:
   - path: "./img/hypnosynth_logo_white.png"
     name: "PlotLogo"
   - path: "./img/VAT.png"
     name: "VAT_test"
     filter: nearest
   - path: "./img/IBL.png"
     name: "IBL"
     filter: nearest
   - path: "./img/vertex_code.png"
     name: "VertexCode"
     filter: nearest
