stages:
  - vs: "./shaders/vertex.glsl"
    mode: "LINE_STRIP"
    line_width: 2
    count: 1000
    target: "vertex"
    
  - fs: "./shaders/scene1.glsl"
    target: "scene1"

  
  # - fs: "./shaders/CellerAutomaton.glsl"
  #   target: "celler"
  
  - fs: "./shaders/raytracing.glsl"
    target: "raytracing"
    float: true

  - fs: "./shaders/logo.glsl"
    target: "logo_layer"

  - fs: "./shaders/accumulate_layer.glsl"
    target: "accumulate_layer"
    float: true

  - fs: "./shaders/combine_layer.glsl"
    target: "combine_layer"

  - fs: "./shaders/bloom_layer.glsl"
    target: "bloom_layer"

  - fs: "./shaders/bloom_layer_gauss.glsl"
    target: "bloom_gauss"

  - fs: "./shaders/bloom_layer_combine.glsl"
    target: "bloom_combine"

  - fs: "./shaders/postEffect_layer.glsl"

images:
   - path: "./img/Plot.png"
     name: "PlotLogo"
   - path: "./img/VAT_Umishida.png"
     name: "VAT_test"
     filter: nearest
